global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - indicator_insight_api:8000