# docker-compose.yml
version: '3'

services:
  indicator_insight_api:
    build: .
    ports:
      - "8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    env_file:
      - ./config/.env
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo
    ports:
      - "27018:27017"

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    depends_on:
      - indicator_insight_api
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
