# docker-compose.yml
version: '3'

services:
  indicator_insight_api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo
    ports:
      - "27018:27017"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
